
project_id = "uzaeyfougoeohqlysbkn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://uzaeyfougoeohqlysbkn.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

[db]
enabled = true
port = 54322
major_version = 15

[functions.audio-to-text]
verify_jwt = false

[functions.lumi-conversation]
verify_jwt = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
