// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzaeyfougoeohqlysbkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YWV5Zm91Z29lb2hxbHlzYmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTk0NDYsImV4cCI6MjA2NTA3NTQ0Nn0.ZtavceUxnTpRpeAyDq_JgpfJZqXlKDatg9cnUwvFkUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);