// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trthcbhowgyuvpzwglvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRydGhjYmhvd2d5dXZwendnbHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzM1NDIsImV4cCI6MjA2NDU0OTU0Mn0.g5wRXVH0fYjIcMK64OAuEKobb3TaAyojjK3cRdShoyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);